server:
  port: 8082
  error:
    include-message: always
    include-exception: true

spring:
  application:
    name: execution-engine

services:
  cost-tracker:
    url: ${COST_TRACKER_URL}

groq:
  api:
    key: ${GROQ_API_KEY:}
  model: ${GROQ_MODEL:llama3-8b-8192}