---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ratio
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: john0553/auth-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ratio-db-secret
                  key: url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: ratio-db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ratio-db-secret
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  namespace: ratio
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP