---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-tracker
  namespace: ratio
  labels:
    app: cost-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-tracker
  template:
    metadata:
      labels:
        app: cost-tracker
    spec:
      containers:
        - name: cost-tracker
          image: john0553/cost-tracker:latest
          ports:
            - containerPort: 8083
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ratio-db-secret
                  key: url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: ratio-db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ratio-db-secret
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cost-tracker-service
  namespace: ratio
  labels:
    app: cost-tracker
spec:
  selector:
    app: cost-tracker
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP