apiVersion: v1
kind: Secret
metadata:
  name: ratio-db-secret
  namespace: ratio
type: Opaque
stringData:
  url: "jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres"
  username: "postgres.sevxqiufetmuqghfojxk"
  password: "GloriousJohn231@"
---
apiVersion: v1
kind: Secret
metadata:
  name: ratio-groq-secret
  namespace: ratio
type: Opaque
stringData:
  api-key: "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"